### ISSUE TITLE
Ecotone Hardfork Tracker

### ISSUE THREAD

**Issue by ImTei** [sunnyside-io/op-erigon#123]
# Implementation
- [ ] Merge erigon upstream
- [x] Add Ecotone timestamp in chain config
- [x] L2 Cancun support
  - https://github.com/ethereum-optimism/op-geth/pull/205
    - explicitly disable Blob transactions
    - explicitly change signer methods to use London signer instead of Cancun signer
    - activate Cancun when Ecotone superchain fork is set
    - update superchain-registry dep
-  [x] Ecotone l1 cost function
  - https://github.com/ethereum-optimism/protocol-quest/issues/65
    - https://github.com/ethereum-optimism/op-geth/pull/203
  - https://github.com/ethereum-optimism/protocol-quest/issues/66
    - https://github.com/ethereum-optimism/op-geth/pull/210
- [x] Extend engine API (Add parent beacon block root)
  - https://github.com/ethereum-optimism/optimism/pull/8852
  - https://github.com/ethereum-optimism/op-geth/pull/214

# Reference
- https://github.com/ethereum-optimism/protocol-quest/issues/71
- https://github.com/ethereum-optimism/optimism/issues/8701
