### ISSUE TITLE
Canyon Hardfork Tracker

### ISSUE THREAD

**Issue by pcw109550** [sunnyside-io/op-erigon#96]
# Canyon Hardfork Tracker

OP-Goerli Activation time: `1699981200`

- https://github.com/testinprod-io/op-erigon/pull/105
- https://github.com/testinprod-io/erigon-lib/pull/28

## Features

- [x] Cleanup overrides & add the canyon network upgrade
    - op-geth ref: https://github.com/ethereum-optimism/op-geth/pull/133
    - Code:
        - https://github.com/testinprod-io/op-erigon/pull/97
        - https://github.com/testinprod-io/erigon-lib/pull/24
        - https://github.com/testinprod-io/erigon-lib/pull/27
        - https://github.com/testinprod-io/op-erigon/pull/103
- [x] L2 Shapella (Shanghai + Capella) hard fork support
    - Issue: https://github.com/ethereum-optimism/optimism/issues/6728
    - op-geth ref: https://github.com/ethereum-optimism/op-geth/pull/171
    - Code:
        - https://github.com/testinprod-io/op-erigon/pull/102
- [x] Change EIP-1559 Parameters for mainnet
    - op-geth ref: https://github.com/ethereum-optimism/op-geth/pull/165 
    - Code:
        - https://github.com/testinprod-io/op-erigon/pull/98
        - https://github.com/testinprod-io/erigon-lib/pull/26
- [x] Receipt hashing bug fix
    - Issue: https://github.com/ethereum-optimism/op-geth/issues/144 
    - op-geth ref: https://github.com/ethereum-optimism/op-geth/pull/152, https://github.com/ethereum-optimism/op-geth/pull/167
    - This may also fix https://github.com/testinprod-io/op-erigon/issues/68 -> No it did not.
    - Code: 
        - https://github.com/testinprod-io/op-erigon/pull/99 
- [x] Create2Deployer Precompile
    - op-geth ref: https://github.com/ethereum-optimism/op-geth/pull/126, https://github.com/ethereum-optimism/op-geth/pull/170
    - code:
        - https://github.com/testinprod-io/op-erigon/pull/101
        - https://github.com/testinprod-io/op-erigon/pull/106
        - https://github.com/testinprod-io/op-erigon/pull/107
- [x] Update op-erigon chainspecs(set canyon hardfork time, EIP1559DenominatorCanyon = 250)
    - op-erigon ref: https://github.com/testinprod-io/op-erigon/pull/59
    - op-geth ref: https://github.com/ethereum-optimism/superchain-registry/pull/28, https://github.com/ethereum-optimism/op-geth/pull/175
    - code:
        - https://github.com/testinprod-io/op-erigon/pull/104
        - https://github.com/testinprod-io/op-erigon/pull/108
- (Optional) Integrate [superchain registry](https://github.com/ethereum-optimism/superchain-registry) to op-erigon
    - op-geth ref: https://github.com/ethereum-optimism/op-geth/pull/113

## Testing

- https://github.com/ethereum-optimism/optimism/pull/7903
- https://github.com/ethereum-optimism/optimism/issues/7731

## References

- https://github.com/ethereum-optimism/optimism/issues/7452
- https://github.com/ethereum-optimism/optimism/issues/6728

**Comment by pcw109550** [comment]
canyon is live on mainnet!
